version: '3.7'

services:
 backend:
  container_name: backend-container
  image: jnkiarie/backend-image:v1.0.3
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - 5000:5000
  environment:
   PORT: 5000
   ME_CONFIG_MONGODB_ADMINUSERNAME:
   ME_CONFIG_MONGODB_ADMINPASSWORD:
   DB_URL:


 client:
  container_name: client-container
  image: jnkiarie/client-image:v1.0.3
  build:
   context: ./client
   dockerfile: Dockerfile

  ports:
   - 3000:3000
  environment:
   PORT: 3000
   USER_NAME:
   USER_PWD:
   DB_URL:
   
  # volume:
  #  - mongo-volume